### ISSUE TITLE
Cannot deposit BTC

### ISSUE THREAD

**Issue by qauntumspirit** [EGaaS/go-egaas-mvp#38]
I have opened an eGaaS account for ICO. However, I do not know how to deposit BTC in order to buy tokens. I have tried selecting wallet balance and scanned the QR code with my Blockchain wallet but it reads 'invalid Bitcoin address'. 

Any assistance you could provide would be most appreciated.

**Comment by c-darwin** [comment]
Hello,
Try to enter the address manually, without QR code.
